services:
  eyeris:
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - render
      - video
    volumes:
      - /sys/class/drm:/sys/class/drm:ro
      - /sys/class/hwmon:/sys/class/hwmon:ro
      - /sys/bus/pci/devices:/sys/bus/pci/devices:ro
